posts/forms.py
from wtforms import Form, StringField, TextAreaField


class PostForm(Form):
    title = StringField('Title')
    body = TextAreaField('Body')

posts/blueprint.py
from flask import Blueprint
from flask import render_template

from models import Post, Tag

from flask import request

from .forms import PostForm

from app import db

from flask import redirect
from flask import url_for

# 14) Специальный декоратор проверки залогиности и приписываем это к create и edit post(потом конфиг)
from flask_security import login_required


# 'posts' - название блюпринта
posts = Blueprint('posts', __name__, template_folder='templates')


@posts.route('/create', methods=['POST', 'GET'])
@login_required
def create_post():
    if request.method == 'POST':
        title = request.form['title']  # 'title' это переменная title из класса PostForm, это то что ввели в форме
        body = request.form['body']

        try:
            post = Post(title=title, body=body)
            db.session.add(post)
            db.session.commit()
        except:
            print('Wrong')
        return redirect(url_for('posts.index'))

    form = PostForm()
    return render_template('posts/create_post.html', form=form)


@posts.route('/<slug>/edit', methods=['POST', 'GET'])
@login_required
def edit_post(slug):
    post = Post.query.filter(Post.slug==slug).first()

    if request.method == 'POST':
        form = PostForm(fromdata=request.form, obj=post)
        form.populate_obj(post)
        db.session.commit()

        return redirect(url_for('posts.post_detail', slug=post.slug))

    form = PostForm(obj=post)
    return render_template('posts/edit.html', form=form, post=post)




@posts.route('/')
def index():
    # 'q' то что мы ввели в base.html Search
    q = request.args.get('q')

    page = request.args.get('page')
    
    if page and page.isdigit():
        page = int(page)
    else:
        page = 1

    if q:
        posts = Post.query.filter(Post.title.contains(q) | Post.body.contains(q)) #.all()
    else:
        posts = Post.query.order_by(Post.created.desc())

    pages = posts.paginate(page=page, per_page=5)

    return render_template('posts/index.html', posts=posts, pages=pages)


@posts.route('/<slug>')
def post_detail(slug):
    post = Post.query.filter(Post.slug == slug).first()
    tags = post.tags
    return render_template('posts/post_detail.html', post=post, tags=tags)


@posts.route('/tag/<slug>')
def tag_detail(slug):
    tag = Tag.query.filter(Tag.slug == slug).first()
    '''all нужет чтобы получть тип списка, без all будет типо BaseQuery.
     Метод all  доступен потому что в ralationship'е 
     мы указали lazy=dynamic что возвращает тип BaseQuery
     и у BaseQuery есть много разных методов'''
    posts = tag.posts.all()
    return render_template('posts/tag_detail.html', tag=tag, posts=posts)

posts/templates/posts/create_post.html
{% extends 'base.html' %}

{% block title %}
    Create new post
{% endblock %}

{% block content_title %}
    New post
{% endblock %}

{% block content %}
    <form action="{{ url_for('posts.create_post') }}" method="POST">
        {% for field in form  %}{# Итерация идет по полям класса PostForm #}
            <div class="form-group">
                {{ field.label(class='control-label') }} {# это наши поля в классе PostForm #}
                {{ field(class='form-control') }}
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-success">Create</button>



    </form>
{% endblock %}

posts/templates/posts/edit.html
{% extends 'base.html' %}

{% block title %}
    Edit post
{% endblock %}

{% block content_title %}
    Edit post
{% endblock %}

{% block content %}
    <form action="{{ url_for('posts.edit_post', slug=post.slug) }}" method="POST">
        {% for field in form  %}{# Итерация идет по полям класса PostForm #}
            <div class="form-group">
                {{ field.label(class='control-label') }} {# это наши поля в классе PostForm #}
                {{ field(class='form-control') }}
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-warning">Edit</button>



    </form>
{% endblock %}

posts/templates/posts/index.html
{% extends 'base.html' %}

{% block title %}
    Blueprint index
{% endblock %}

{% block content_title %}
    Posts
{% endblock %}

{% block content %}
    {% for post in pages.items %}
        <p>
            <a href="{{ url_for('posts.post_detail', slug=post.slug) }}">{{ post.title }}</a>
        </p>
    {% endfor %}
    <nav aria-label="Page navigation example">
        <ul class="pagination">
            <li {% if not pages.has_prev %}class="page-item disabled"{% endif %}><a class="page-link" href="./?page={{ pages.prev_num }}">Previous</a></li>

            <li class="page-item">
                {% for page in pages.iter_pages() %}
                     <li {% if page == pages.page %}class="page-item active"{% endif %}>
                        <a class="page-link" href="./?page={{ page }}">{{ page }}</a>
                    </li>
                {% endfor %}
            </li>

            <li {% if not pages.has_next %}class="page-item disabled"{% endif %}><a class="page-link" href="./?page={{ pages.next_num }}">Next</a></li>
        </ul>
    </nav>
{% endblock %}

posts/templates/posts/post_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ post.title }}
{% endblock %}

{% block content_title %}
    {{ post.title }}
{% endblock %}


{% block content %}
    <div class="tags">
    {% for tag in tags %}
        <a href="{{ url_for('posts.tag_detail', slug=tag.slug) }}"><span class="badge badge-primary">{{ tag.name }}</span></a>
    {% endfor %}
    </div>
    <div class="main-content">
    {{ post.body }}
    </div>
{% endblock %}

posts/templates/posts/tag_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ tag.name }} posts
{% endblock %}

{% block content_title %}
    Posts for "{{ tag.name }}" tag:
{% endblock %}

{% block content %}
    {% for post in posts  %}
        <div class="post">
            {#в posts.tag_detail слово posts это не название папки, а название blueprint'a#}
            <a href="{{ url_for('posts.post_detail', slug=post.slug) }}">{{ post.title }}</a>
        </div>
    {% endfor %}

{% endblock %}